const ADMIN_LABELS: Readonly<Record<string, string>> = {
  active: 'Đang hoạt động',
  paused: 'Tạm dừng',
  locked: 'Đã khóa',
  pending: 'Đang chờ',
  hidden: 'Đã ẩn',
  dismissed: 'Đã bỏ qua',
  received: 'Đã tiếp nhận',
  verifying: 'Đang xác minh',
  collecting_evidence: 'Đang thu thập bằng chứng',
  evaluating: 'Đang đánh giá',
  resolving: 'Đang xử lý',
  notified: 'Đã thông báo',
  resolved: 'Đã giải quyết',
  moderation: 'Kiểm duyệt',
  moderation_report: 'Báo cáo kiểm duyệt',
  complaint: 'Khiếu nại',
  configuration: 'Cấu hình',
  export: 'Yêu cầu xuất',
  user: 'Tài khoản',
  post: 'Bài đăng',
  review: 'Đánh giá',
  message: 'Tin nhắn',
  normal: 'Thông thường',
  high: 'Cao',
  queued: 'Đang xếp hàng',
  ready: 'Sẵn sàng',
  failed: 'Thất bại',
  sent: 'Đã gửi',
  valid: 'Hợp lệ',
  invalid: 'Không hợp lệ',
  weak: 'Yếu',
  medium: 'Trung bình',
  strong: 'Mạnh',
  complainant: 'Bên khiếu nại',
  respondent: 'Bên bị khiếu nại',
  shared: 'Trách nhiệm chung',
  none: 'Không có',
  refund: 'Hoàn tiền',
  compensation: 'Bồi thường',
  redo: 'Thực hiện lại',
  warning: 'Cảnh báo',
  quality: 'Chất lượng',
  payment: 'Thanh toán',
  schedule: 'Lịch trình',
  conduct: 'Hành vi',
  other: 'Khác',
  all: 'Tất cả',
  mine: 'Của tôi',
  unassigned: 'Chưa phân công',
  due_soon: 'Sắp đến hạn',
  overdue: 'Quá hạn',
  'user.locked': 'Khóa tài khoản',
  'user.active': 'Mở khóa tài khoản',
  'moderation.hide': 'Ẩn nội dung',
  'moderation.restore': 'Khôi phục nội dung',
  'moderation.dismiss': 'Bỏ qua báo cáo',
  'inbox.assign': 'Phân công hàng đợi',
  'complaint.verifying': 'Chuyển sang xác minh',
  'complaint.collecting_evidence': 'Yêu cầu bằng chứng',
  'complaint.evaluating': 'Chuyển sang đánh giá',
  'complaint.decision': 'Ghi quyết định khiếu nại',
  'complaint.notified': 'Thông báo các bên',
  'complaint.party_response': 'Ghi phản hồi của bên liên quan',
  'complaint.resolved': 'Đóng khiếu nại',
  'configuration.save': 'Lưu cấu hình',
  'configuration.restore': 'Khôi phục cấu hình',
  'audit.export_requested': 'Yêu cầu xuất nhật ký',
};

export function adminLabel(value: string | null | undefined, fallback = 'Chưa xác định'): string {
  if (!value) return fallback;
  return ADMIN_LABELS[value] ?? value;
}

export function adminBooleanLabel(value: boolean): string {
  return value ? 'Có' : 'Không';
}
